# Generated by Django 5.1.7 on 2025-04-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0012_merge_20250402_0213'),
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('receta_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_receta', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('preparacion', models.TextField(default='Sin descripción')),
                ('porciones_galletas', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('recetasinsumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.IntegerField(default=0)),
                ('unidad_medida', models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas')], max_length=10, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
            ],
        ),
    ]
