# Generated by Django 5.1.7 on 2025-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0004_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo')], default='efectivo', max_length=15),
        ),
    ]
