# Generated by Django 5.1.7 on 2025-04-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
        ('ventas_app', '0006_venta_estado_entrega_venta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto'),
        ),
    ]
