# Generated by Django 5.1.7 on 2025-04-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0007_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estatus_venta',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
