# Generated by Django 5.1.5 on 2025-04-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0002_remove_proveedor_dia_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='dia_entrega',
        ),
    ]
