# Generated by Django 5.1.7 on 2025-04-08 18:42

import django.db.models.deletion
import recetas_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0001_initial'),
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('receta_id', models.AutoField(primary_key=True, serialize=False)),
                ('foto_receta', models.ImageField(blank=True, null=True, upload_to='recetas/', validators=[recetas_app.models.validate_image_extension])),
                ('preparacion', models.TextField(default='Sin descripción')),
                ('porciones_galletas', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('recetasinsumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
            ],
        ),
    ]
