# Generated by Django 5.1.7 on 2025-03-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0011_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(default='Receta sin nombre', max_length=200)),
                ('foto_receta', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('preparacion', models.TextField(default='Sin descripción')),
                ('porciones_galletas', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecetaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.recetas')),
            ],
        ),
    ]
