# Generated by Django 5.1.7 on 2025-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetainsumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas')], max_length=10, null=True),
        ),
    ]
