# Generated by Django 5.1.7 on 2025-04-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto'),
        ),
    ]
