# Generated by Django 5.1.5 on 2025-04-05 00:35

import recetas_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='foto_receta',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/', validators=[recetas_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('ml', 'Mililitros'), ('bultos', 'Bultos'), ('pz', 'Piezas')], max_length=10, null=True),
        ),
    ]
