# Generated by Django 5.1.5 on 2025-04-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetainsumo',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10, null=True),
        ),
    ]
