# Generated by Django 5.1.7 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0002_alter_receta_foto_receta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetainsumo',
            name='unidad_medida',
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad_necesaria',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
