# Generated by Django 5.1.7 on 2025-04-01 17:56

from django.db import migrations

def asignar_productos(apps, schema_editor):
    Receta = apps.get_model('recetas_app', 'Receta')
    Producto = apps.get_model('productos_app', 'Producto')
    
    # Ejemplo: Asigna todas las recetas al primer producto (ajusta según tu lógica)
    producto_default = Producto.objects.first()  # ¡Cambia esto!
    
    for receta in Receta.objects.filter(producto__isnull=True):
        receta.producto = producto_default
        receta.save()

class Migration(migrations.Migration):
    dependencies = [
        ('recetas_app', '0003_remove_receta_nombre_receta_alter_receta_producto'),  # Reemplaza con el nombre real
    ]
    
    operations = [
        migrations.RunPython(asignar_productos),
    ]
