# Generated by Django 5.1.7 on 2025-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0004_asignar_productos_a_recetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad_necesaria',
            field=models.IntegerField(default=0),
        ),
    ]
