# Generated by Django 5.1.7 on 2025-04-03 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_app', '0001_initial'),
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ventas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='ventas_app.venta'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente'),
        ),
    ]
