<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-08 18:42
=======
# Generated by Django 5.1.7 on 2025-04-08 15:02
>>>>>>> origin/isaac

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_app', '0001_initial'),
        ('ventas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ventas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='ventas_app.venta'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente'),
        ),
    ]
