# Generated by Django 5.1.7 on 2025-04-06 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0003_remove_cliente_usuario_remove_cliente_ventas_and_more'),
        ('ventas_app', '0005_alter_venta_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
