# Generated by Django 5.1.7 on 2025-04-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0004_producto_alter_cliente_options_alter_cliente_usuario_and_more'),
        ('ventas_app', '0008_alter_venta_estatus_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ventas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='ventas_app.venta'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
