# Generated by Django 5.1.7 on 2025-04-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0005_remove_detalleventa_producto_and_more'),
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pz', 'pz')], max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
        ),
    ]
