# Generated by Django 5.1.7 on 2025-04-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0005_remove_perfilusuario_usuario_and_more'),
        ('ventas_app', '0006_alter_venta_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
