# Generated by Django 5.1.5 on 2025-04-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_app', '0001_initial'),
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('estatus_venta', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('ticket', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo')], default='efectivo', max_length=15)),
                ('estado_entrega', models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pz', 'pz')], max_length=2)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_app.venta')),
            ],
        ),
    ]
