# Generated by Django 5.1.7 on 2025-03-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
