# Generated by Django 5.1.7 on 2025-03-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_venta_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='ticket',
            field=models.TextField(blank=True, null=True),
        ),
    ]
