# Generated by Django 5.1.5 on 2025-04-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='observaciones',
        ),
    ]
