# Generated by Django 5.1.7 on 2025-04-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_remove_venta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('pz', 'pz'), ('1kg', '1kg'), ('700gr', '700gr')], max_length=6),
        ),
    ]
