# Generated by Django 5.1.7 on 2025-04-06 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0003_remove_cliente_usuario_remove_cliente_ventas_and_more'),
        ('ventas_app', '0004_alter_detalleventa_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.perfilusuario'),
        ),
    ]
