# Generated by Django 5.1.7 on 2025-04-07 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0005_remove_perfilusuario_usuario_and_more'),
        ('ventas_app', '0005_alter_venta_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente_app.cliente'),
        ),
    ]
