# Generated by Django 5.1.7 on 2025-04-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0005_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_entrega',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
