# Generated by Django 5.1.5 on 2025-04-02 00:24

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido_materno',
            field=models.CharField(default='Sin apellido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido_paterno',
            field=models.CharField(default='Sin apellido', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(default=now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
