# Generated by Django 5.1.5 on 2025-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('ml', 'Mililitros'), ('bultos', 'Bultos'), ('pz', 'Piezas')], max_length=10),
        ),
    ]
