# Generated by Django 5.1.5 on 2025-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('pz', 'Piezas')], max_length=10),
        ),
    ]
