# Generated by Django 5.1.5 on 2025-03-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0002_alter_detallecompra_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
