# Generated by Django 5.1.7 on 2025-04-01 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0004_alter_detallecompra_unidad_medida_productoalmacenado_and_more'),
        ('insumos_app', '0008_insumos_conversion_bulto_insumos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoalmacenado',
            name='insumo',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='ProductoAlmacenado',
        ),
    ]
