# Generated by Django 5.1.7 on 2025-04-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0005_remove_productoalmacenado_insumo_compra_cantidad_and_more'),
        ('insumos_app', '0008_insumos_conversion_bulto_insumos_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='unidad_medida',
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras_app.compra')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
    ]
