# Generated by Django 5.1.7 on 2025-03-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.TextField(max_length=200)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('pz', 'Piezas')], max_length=10)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores_app.proveedor')),
            ],
        ),
    ]
