# Generated by Django 5.1.5 on 2025-04-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
            ],
        ),
    ]
