# Generated by Django 5.1.7 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0002_alter_insumos_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos'), ('pz', 'Piezas')], max_length=10),
        ),
    ]
