# Generated by Django 5.1.7 on 2025-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0004_rename_unidad_insumos_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
