# Generated by Django 5.1.7 on 2025-03-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0006_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
