# Generated by Django 5.1.7 on 2025-04-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0007_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='fecha_caducidad',
        ),
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
