# Generated by Django 5.1.5 on 2025-03-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0007_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='conversion_bulto',
            field=models.DecimalField(decimal_places=3, default=50000, max_digits=10),
        ),
        migrations.AddField(
            model_name='insumos',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], default='g', max_length=10),
        ),
    ]
