# Generated by Django 5.1.7 on 2025-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0011_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='fecha_caducidad',
        ),
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
