# Generated by Django 5.1.7 on 2025-04-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0008_remove_insumos_fecha_caducidad_and_more'),
        ('insumos_app', '0011_alter_insumos_cantidad_disponible'),
    ]

    operations = [
    ]
