# Generated by Django 5.1.7 on 2025-04-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0008_insumos_conversion_bulto_insumos_estado_and_more'),
        ('insumos_app', '0012_merge_20250402_0213'),
    ]

    operations = [
    ]
