# Generated by Django 5.1.7 on 2025-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0013_merge_20250402_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='conversion_bulto',
        ),
        migrations.RemoveField(
            model_name='insumos',
            name='estado',
        ),
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10),
        ),
    ]
