# Generated by Django 5.1.7 on 2025-04-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0014_remove_insumos_conversion_bulto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
