# Generated by Django 5.1.7 on 2025-03-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('pz', 'Piezas')], max_length=3)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
