# Generated by Django 5.1.7 on 2025-04-08 18:42

import productos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_medida', models.CharField(choices=[('pz', 'Piezas')], default='pz', max_length=3)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos/', validators=[productos_app.models.validate_image_extension])),
            ],
        ),
    ]
