# Generated by Django 5.1.7 on 2025-04-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
