# Generated by Django 5.1.7 on 2025-04-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
    ]
