# Generated by Django 5.1.7 on 2025-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0002_alter_producto_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('pz', 'Piezas')], default='pz', max_length=3),
        ),
    ]
