# Generated by Django 5.1.7 on 2025-04-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0002_producto_imagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_producto',
        ),
    ]
