# Generated by Django 5.1.7 on 2025-04-04 23:25

import productos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0003_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[productos_app.models.validate_image_extension]),
        ),
    ]
