# Generated by Django 5.1.7 on 2025-04-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0004_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(null=True),
        ),
    ]
