# Generated by Django 5.1.7 on 2025-04-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0005_alter_producto_fecha_caducidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
