# Generated by Django 5.1.7 on 2025-04-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0006_alter_producto_fecha_caducidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_caducidad',
        ),
    ]
