# Generated by Django 5.1.5 on 2025-03-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0007_alter_insumos_cantidad_disponible'),
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='proveedores_app.proveedor')),
            ],
            options={
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('detalle_compra_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, to='compras_app.compra')),
                ('insumo', models.ForeignKey(db_column='insumo_id', on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('compra', models.OneToOneField(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, to='compras_app.compra')),
            ],
            options={
                'db_table': 'pago_proveedor',
            },
        ),
    ]
