# Generated by Django 5.1.5 on 2025-03-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0001_initial'),
        ('insumos_app', '0007_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos'),
        ),
    ]
