# Generated by Django 5.1.5 on 2025-03-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_app', '0003_detallecompra_unidad_medida'),
        ('insumos_app', '0008_insumos_conversion_bulto_insumos_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='unidad_medida',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10),
        ),
        migrations.CreateModel(
            name='ProductoAlmacenado',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('litros', 'Litros'), ('bultos', 'Bultos')], max_length=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
            ],
            options={
                'db_table': 'producto_almacenado',
            },
        ),
        migrations.DeleteModel(
            name='PagoProveedor',
        ),
    ]
