# Generated by Django 5.1.7 on 2025-04-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0001_initial'),
        ('recetas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cantidad_producida', models.PositiveIntegerField(default=0)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('lote_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_galletas', models.PositiveIntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible para venta'), ('por_caducar', 'Próximo a caducar'), ('caducado', 'Caducado (merma)')], default='disponible', max_length=20)),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion_app.produccion')),
            ],
            options={
                'verbose_name': 'Lote de Producción',
                'verbose_name_plural': 'Lotes de Producción',
                'ordering': ['fecha_caducidad'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumos',
            fields=[
                ('consumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion_app.produccion')),
            ],
        ),
    ]
