# Generated by Django 5.1.7 on 2025-03-28 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos_app', '0007_alter_insumos_cantidad_disponible'),
        ('productos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('produccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('lote_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_galletas', models.PositiveIntegerField()),
                ('fecha_caducidad', models.DateField()),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion_app.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoInsumos',
            fields=[
                ('consumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos_app.insumos')),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion_app.produccion')),
            ],
        ),
    ]
