# Generated by Django 5.1.7 on 2025-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={'ordering': ['estado', 'fecha_caducidad'], 'verbose_name': 'Lote de Producción', 'verbose_name_plural': 'Lotes de Producción'},
        ),
    ]
