# Generated by Django 5.1.7 on 2025-04-05 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={},
        ),
    ]
