# Generated by Django 5.1.7 on 2025-03-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='cantidad_producida',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
