# Generated by Django 5.1.7 on 2025-04-03 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0002_produccion_cantidad_producida'),
        ('recetas_app', '0006_alter_recetainsumo_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='producto',
        ),
        migrations.AddField(
            model_name='produccion',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produccion',
            name='receta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recetas_app.receta'),
            preserve_default=False,
        ),
    ]
