# Generated by Django 5.1.7 on 2025-04-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0002_alter_loteproduccion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={'ordering': ['fecha_caducidad'], 'verbose_name': 'Lote de Producción', 'verbose_name_plural': 'Lotes de Producción'},
        ),
    ]
