# Generated by Django 5.1.7 on 2025-04-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0003_remove_produccion_producto_produccion_costo_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={'ordering': ['fecha_caducidad'], 'verbose_name': 'Lote de Producción', 'verbose_name_plural': 'Lotes de Producción'},
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible para venta'), ('por_caducar', 'Próximo a caducar'), ('caducado', 'Caducado (merma)')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
