# Generated by Django 5.1.7 on 2025-04-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0003_alter_loteproduccion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='costo_total',
        ),
    ]
