# Generated by Django 5.1.7 on 2025-04-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0003_loteproduccion_produccion__estado_bfc41c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loteproduccion',
            name='produccion__estado_bfc41c_idx',
        ),
        migrations.RemoveIndex(
            model_name='loteproduccion',
            name='produccion__fecha_c_f85aaf_idx',
        ),
    ]
