# Generated by Django 5.1.7 on 2025-04-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0004_remove_loteproduccion_produccion__estado_bfc41c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loteproduccion',
            index=models.Index(fields=['estado'], name='produccion__estado_bfc41c_idx'),
        ),
        migrations.AddIndex(
            model_name='loteproduccion',
            index=models.Index(fields=['fecha_caducidad'], name='produccion__fecha_c_f85aaf_idx'),
        ),
    ]
