# Generated by Django 5.1.7 on 2025-04-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0004_alter_loteproduccion_options_loteproduccion_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproduccion',
            name='fecha_registro',
        ),
    ]
