# Generated by Django 5.1.7 on 2025-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0005_remove_loteproduccion_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumoinsumos',
            name='cantidad_usada',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
