# Generated by Django 5.1.7 on 2025-04-10 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0005_loteproduccion_produccion__estado_bfc41c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduccion',
            options={'ordering': ['fecha_caducidad'], 'verbose_name': 'Lote de Producción', 'verbose_name_plural': 'Lotes de Producción'},
        ),
        migrations.RemoveIndex(
            model_name='loteproduccion',
            name='produccion__estado_bfc41c_idx',
        ),
        migrations.RemoveIndex(
            model_name='loteproduccion',
            name='produccion__fecha_c_f85aaf_idx',
        ),
    ]
