# Generated by Django 5.1.7 on 2025-04-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0006_alter_loteproduccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='merma_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
