# Generated by Django 5.1.7 on 2025-04-03 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0006_alter_consumoinsumos_cantidad_usada'),
        ('productos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProduccion',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos_app.producto')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante')),
            ],
        ),
    ]
