# Generated by Django 5.1.7 on 2025-04-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion_app', '0007_solicitudproduccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudProduccion',
        ),
    ]
