# Generated by Django 5.1.7 on 2025-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0002_remove_insumos_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='nombre_insumo',
            field=models.CharField(max_length=200),
        ),
    ]
