# Generated by Django 5.1.7 on 2025-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0003_alter_insumos_nombre_insumo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumos',
            old_name='unidad',
            new_name='unidad_medida',
        ),
        migrations.AddField(
            model_name='insumos',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
