# Generated by Django 5.1.7 on 2025-03-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos_app', '0008_alter_insumos_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad_disponible',
            field=models.IntegerField(default=0),
        ),
    ]
