# Generated by Django 5.1.7 on 2025-03-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='cliente', max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estatus_user', models.IntegerField(default=1)),
            ],
        ),
    ]
