# Generated by Django 5.1.5 on 2025-04-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0004_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
